// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package org.js.grpc.person;

public interface FindPersonRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FindPersonRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
