// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package org.js.grpc.person;

public interface FindPersonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FindPersonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   */
  int getAge();

  /**
   * <code>bool sex = 3;</code>
   */
  boolean getSex();
}
